on:
  push:

jobs:
  dind:
    runs-on: ubuntu-latest

    env:
      DOCKER_CONFIG: $HOME/.docker

    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - uses: docker://docker
        with:
          entrypoint: docker
          args: pull "ghcr.io/twiddler/my-alpine:3.13"
